name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node 12.16.3
      uses: actions/setup-node@v1
      with:
        node-version: '12.16.3'
   
    - name: Install node dependencies
      run: npm ci

    - name: Run tests
      run: npm run test
